### ISSUE TITLE
Can I use it in ubuntu?

### ISSUE THREAD

**Issue by wzyinparis** [carlosedubarreto/b3d_mocap_import#25]
Hello, thank you for your work.
Can I use it in ubuntu?

**Comment by carlosedubarreto** [comment]
Hi, I think you wont have problems using there. But if you have, please send the error so I can take a look in the problem

**Comment by wzyinparis** [comment]
I tried your fbx_output_FRANKMOCAP.zip in https://github.com/facebookresearch/frankmocap/issues/50#issuecomment-752014586. 

How I use it? I used this command and got this error.

python lib/utils/fbx_output_FRANKMOCAP.py --input ../frankmocap/mocap_output/mocap/scene_00130_prediction_result.pkl --output output/sample_video/fbx_output.fbx --fps_source 30 --fps_target 30 --gender male --person_id 0
Input path: /home/predictive/Documents/VIBE/../frankmocap/mocap_output/mocap/scene_00130_prediction_result.pkl
Output path: /home/predictive/Documents/VIBE/output/sample_video/fbx_output.fbx
Processing: /home/predictive/Documents/VIBE/../frankmocap/mocap_output/mocap/scene_00130_prediction_result.pkl
Traceback (most recent call last):
  File "lib/utils/fbx_output_FRANKMOCAP.py", line 349, in <module>
    person_id=args.person_id
  File "lib/utils/fbx_output_FRANKMOCAP.py", line 171, in process_poses
    list_dir = os.listdir(pkl_path)
FileNotFoundError: [Errno 2] No such file or directory: 'mocap_FRANK\\'



> Hi, I think you wont have problems using there. But if you have, please send the error so I can take a look in the problem

**Comment by carlosedubarreto** [comment]
LOL, I dont suport that code 😊
It was just an example that the person that was going to use had to change lots of things.

But on top of that I created mocap import addon.

You can downlod from this github or via gumroad

https://carlosedubarreto.gumroad.com/l/mocap_import

please try it, and if you have problems, send them here so I can see what needs to be fixed.
