### ISSUE TITLE
TypeError: Converting py args to operator properties: : keyword "scale" unrecognized

### ISSUE THREAD

**Issue by daoboke** [carlosedubarreto/b3d_mocap_import#33]
Hi I don't know how to solve the following problem
Traceback (most recent call last):
  File "/home/dms/.config/blender/2.83/scripts/addons/b3d_mocap_import/load_mocap.py", line 1044, in execute
    create_dots('Point',49)
  File "/home/dms/.config/blender/2.83/scripts/addons/b3d_mocap_import/load_mocap.py", line 765, in create_dots
    bpy.ops.mesh.primitive_plane_add(enter_editmode=True, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
  File "/home/dms/blender-2.83.19-linux-x64/2.83/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "scale" unrecognized

location: <unknown location>:-1

**Comment by carlosedubarreto** [comment]
Hello,
What are you trying to do with the addon? Are you trying to import some mocap data?
Can you share it for me to test?

**Comment by daoboke** [comment]
Hi, I just solved this problem, it was due to blender version. The first time I used 2.83LTS and then used the latest 3.1.2 version, there was no problem (ubuntu environment)
My requirement is to use this plugin to import the .pkl generated in frankmocap into blender and generate .bvh or .fbx.
Now my problem is that I don't know much about using this plugin,
1. For example, if there is already a bone animation, can i import a skinned model?
2. Does this plugin support .pkl in smplx format?
3. Take the liberty to ask if there are more detailed instructions for use.
thanks a lot

**Comment by carlosedubarreto** [comment]
I'm glad you solved the problem.

Lets go with the topics.
1- I think you are refereing to retageting, where you get an armature animation and make that animation to drive the movement on another character.

You can find lots of tutorials on how to do that with free and paid addons.

If you want to go on the free path, I suggest you to looks at Rokoko addon. and see some tutorial on it.

For the paid route, the best I know is Auto Rig Pro. Its an mazing addon, that covers much more than retargeting, it can also rig your character. It worth a look.

2-It think it does, but i think you will have to export a SMPLX version of the FBX file. You will have to go to the SMPLX site, get the blender SMPLX addon, generate the model that you want and export it as FBX. And you will use it in the addon.

To be honest I dont remember how to do it in the addon because I made 2 addons for easymocap, I did the MOCAP_IMPORT and the CEB EASYMOCAP, . CEB Easymocap is the most recent one and it deals only with Easymocap.

3-I didnt understand this third topic. 😅
