### ISSUE TITLE
EasyMocap errors

### ISSUE THREAD

**Issue by samuelling2** [carlosedubarreto/b3d_mocap_import#37]
May I ask why when I extract the demo videos:

`(easymocap) C:\Users\Samuel\mocap\EasyMocap>python scripts/preprocess/extract_video.py 0_input\sample`

and it shows the json files in the annots folder are skipped:

`cameras:  01 02 03 04 05 06 07 08 09 10 11 13 14 16 17 18 20 21 23
skip  0_input\sample\annots\01
skip  0_input\sample\annots\02
skip  0_input\sample\annots\03
skip  0_input\sample\annots\04
skip  0_input\sample\annots\05
skip  0_input\sample\annots\06
skip  0_input\sample\annots\07
skip  0_input\sample\annots\08
skip  0_input\sample\annots\09
skip  0_input\sample\annots\10
skip  0_input\sample\annots\11
skip  0_input\sample\annots\13
skip  0_input\sample\annots\14
skip  0_input\sample\annots\16
skip  0_input\sample\annots\17
skip  0_input\sample\annots\18
skip  0_input\sample\annots\20
skip  0_input\sample\annots\21
skip  0_input\sample\annots\23`

 Does it matter?

and i run the next code (#2.1 example for SMPL reconstruction): 

`(easymocap) C:\Users\Samuel\mocap\EasyMocap>python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`

it shows an error:

`Traceback (most recent call last):
  File "C:\Users\Samuel\mocap\EasyMocap\apps\demo\mv1p.py", line 11, in <module>
    from easymocap.pipeline import smpl_from_keypoints3d2d
  File "c:\users\samuel\mocap\easymocap\easymocap\pipeline\__init__.py", line 1, in <module>
    from .basic import smpl_from_keypoints3d, smpl_from_keypoints3d2d
  File "c:\users\samuel\mocap\easymocap\easymocap\pipeline\basic.py", line 8, in <module>
    from ..pyfitting import optimizeShape, optimizePose2D, optimizePose3D
  File "c:\users\samuel\mocap\easymocap\easymocap\pyfitting\__init__.py", line 9, in <module>
    from .optimize_mirror import optimizeMirrorDirect, optimizeMirrorSoft
  File "c:\users\samuel\mocap\easymocap\easymocap\pyfitting\optimize_mirror.py", line 10, in <module>
    from ..dataset.mirror import flipSMPLPoses, flipPoint2D, flipSMPLParams
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\__init__.py", line 11, in <module>
    from .mv1pmf_mirror import MV1PMF_Mirror
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mv1pmf_mirror.py", line 14, in <module>
    from .mirror import calc_mirror_transform, flipSMPLParams, mirrorPoint3D, flipPoint2D, mirror_Rh
  File "c:\users\samuel\mocap\easymocap\easymocap\dataset\mirror.py", line 18, in <module>
    FLIP_SMPL_VERTICES = np.loadtxt(join(os.path.dirname(__file__), 'smpl_vert_sym.txt'), dtype=np.int)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?`
![image](https://user-images.githubusercontent.com/116366411/212539209-0877b622-cfad-4ea1-a07b-bb9e71d1cc2b.png)

May I ask how do i fix this?

**Comment by carlosedubarreto** [comment]
I dont have an aswer to you about it. Its been years since I dont touch this code. Maybe its something that needs update.

As it would be hard to go back on this code, I would suggest you to try CEB Easymocap Multicam https://carlosedubarreto.gumroad.com/l/ceb_easymocap_multicam

or CEB easymocap monocular.
https://carlosedubarreto.gumroad.com/l/ceb_em_monocular

You can get then for free on those links I've pasted and probably they will be easier use.
